"""Thin Anthropic wrapper used by every debate agent."""

from __future__ import annotations

import os
from typing import Any

from anthropic import Anthropic
from dotenv import load_dotenv

load_dotenv()

_DEFAULT_MODEL = os.getenv("DEBATE_MODEL", "claude-sonnet-4-6")
_client = Anthropic()


def build_messages(
    artifact: dict[str, Any],
    history: list[dict[str, Any]],
    extra_context: dict[str, str] | None = None,
) -> list[dict[str, Any]]:
    """Build the user-side message list for one agent call.

    The artifact block (and optional extra_context block) are wrapped in a
    single user turn and marked with cache_control so they stay warm across
    rounds. History turns are appended as user messages — each carries `by`
    so the receiving agent knows who said what.
    """
    blocks: list[dict[str, Any]] = [
        {
            "type": "text",
            "text": _format_artifact(artifact),
            "cache_control": {"type": "ephemeral"},
        }
    ]
    if extra_context:
        blocks.append(
            {
                "type": "text",
                "text": _format_extra_context(extra_context),
                "cache_control": {"type": "ephemeral"},
            }
        )

    messages: list[dict[str, Any]] = [{"role": "user", "content": blocks}]

    for turn in history:
        messages.append(
            {
                "role": "user",
                "content": [{"type": "text", "text": _format_turn(turn)}],
            }
        )

    return messages


def call(
    *,
    system: str,
    artifact: dict[str, Any],
    history: list[dict[str, Any]],
    extra_context: dict[str, str] | None = None,
    model: str | None = None,
    max_tokens: int = 2048,
) -> str:
    """Call the LLM and return its text response.

    `system` is also cached so an agent re-using it across rounds gets a hit.
    `extra_context` is an optional {filename: contents} map appended to the
    cacheable user prefix; used by the author role to ship seed_*.py.
    """
    messages = build_messages(artifact, history, extra_context)
    response = _client.messages.create(
        model=model or _DEFAULT_MODEL,
        max_tokens=max_tokens,
        system=[{"type": "text", "text": system, "cache_control": {"type": "ephemeral"}}],
        messages=messages,
    )
    return "".join(
        block.text for block in response.content if getattr(block, "type", None) == "text"
    )


def _format_artifact(artifact: dict[str, Any]) -> str:
    return (
        "You are reviewing a Triton kernel generated by an autonomous agent.\n"
        f"Generator reported passed={artifact.get('passed')}.\n"
        f"Session directory (for evidence lookups): {artifact.get('session_dir')}\n\n"
        "=== KERNEL CODE ===\n"
        f"{artifact.get('kernel_code', '')}\n\n"
        "=== TEST CODE (used by the generator to claim correctness) ===\n"
        f"{artifact.get('test_code', '')}\n"
    )


def _format_turn(turn: dict[str, Any]) -> str:
    return f"[round {turn.get('round')}] {turn.get('by')}:\n{turn.get('text', '')}"


def _format_extra_context(extra: dict[str, str]) -> str:
    sections = ["=== EXTRA CONTEXT (kernel evolution artifacts) ==="]
    for name, content in extra.items():
        sections.append(f"\n--- {name} ---\n{content}")
    return "\n".join(sections)
