"""Thin Anthropic wrapper used by every debate agent."""

from __future__ import annotations

import os
from typing import Any

from anthropic import Anthropic
from dotenv import load_dotenv

load_dotenv()

_DEFAULT_MODEL = os.getenv("DEBATE_MODEL", "claude-sonnet-4-6")
_client = Anthropic()


def build_messages(
    artifact: dict[str, Any],
    history: list[dict[str, Any]],
    extra_context: dict[str, str] | None = None,
) -> list[dict[str, Any]]:
    """Build the user-side message list for one agent call.

    The artifact block (and optional extra_context block) are wrapped in a
    single user turn and marked with cache_control so they stay warm across
    rounds. History turns are appended as user messages — each carries `by`
    so the receiving agent knows who said what.
    """
    blocks: list[dict[str, Any]] = [
        {
            "type": "text",
            "text": _format_artifact(artifact),
            "cache_control": {"type": "ephemeral"},
        }
    ]
    if extra_context:
        blocks.append(
            {
                "type": "text",
                "text": _format_extra_context(extra_context),
                "cache_control": {"type": "ephemeral"},
            }
        )

    messages: list[dict[str, Any]] = [{"role": "user", "content": blocks}]

    for turn in history:
        messages.append(
            {
                "role": "user",
                "content": [{"type": "text", "text": _format_turn(turn)}],
            }
        )

    return messages


def call(
    *,
    system: str,
    artifact: dict[str, Any],
    history: list[dict[str, Any]],
    extra_context: dict[str, str] | None = None,
    model: str | None = None,
    max_tokens: int = 2048,
) -> str:
    """Call the LLM and return its text response.

    `system` is also cached so an agent re-using it across rounds gets a hit.
    `extra_context` is an optional {filename: contents} map appended to the
    cacheable user prefix; used by the author role to ship seed_*.py.
    """
    messages = build_messages(artifact, history, extra_context)
    response = _client.messages.create(
        model=model or _DEFAULT_MODEL,
        max_tokens=max_tokens,
        system=[{"type": "text", "text": system, "cache_control": {"type": "ephemeral"}}],
        messages=messages,
    )
    return "".join(
        block.text for block in response.content if getattr(block, "type", None) == "text"
    )


def oneshot(
    system: str,
    user: str,
    *,
    model: str | None = None,
    max_tokens: int = 4096,
) -> str:
    """Plain one-off system+user call. No caching, no history — used for
    standalone tasks like generating a recheck test for a single kernel.
    """
    response = _client.messages.create(
        model=model or _DEFAULT_MODEL,
        max_tokens=max_tokens,
        system=system,
        messages=[{"role": "user", "content": user}],
    )
    return "".join(
        block.text for block in response.content if getattr(block, "type", None) == "text"
    )


def _format_artifact(artifact: dict[str, Any]) -> str:
    status = artifact.get("status", "unknown")
    rounds = artifact.get("rounds")
    passed = artifact.get("passed")

    parts = [
        "You are reviewing a Triton kernel generated by an autonomous agent.",
        "",
        "=== GENERATOR OUTCOME ===",
        f"passed = {passed}",
        f"status = {status}",
        f"rounds_attempted = {rounds}",
        f"session_dir = {artifact.get('session_dir')}",
        "",
        "=== KERNEL CODE (kernel.py — the final attempt; on failure this is",
        "the best refined version, NOT the seed) ===",
        artifact.get("kernel_code", ""),
        "",
        "=== TEST CODE (test.py — what the generator used to decide pass/fail) ===",
        artifact.get("test_code", ""),
    ]

    # Surface failure evidence when present so debate agents can ground their
    # claims in actual stderr/stdout rather than guessing from kernel code alone.
    error = artifact.get("error") or {}
    error_text = error.get("text") or _legacy_error_text(error)
    if not passed and error_text:
        parts.extend(
            [
                "",
                "=== LAST FAILED ATTEMPT — captured stderr/stdout from the test run ===",
                "(This is ground-truth evidence of WHY the kernel did not pass.",
                "Skeptic: validate concerns against this. Author: explain what it",
                "reveals about kernel behavior. Do not speculate beyond it.)",
                _truncate(error_text, 4000),
            ]
        )

    return "\n".join(parts) + "\n"


def _legacy_error_text(error: dict[str, Any]) -> str:
    """Compose stderr+stdout from generator.py's pre-dataset shape (live runs)."""
    stderr = error.get("stderr") or ""
    stdout = error.get("stdout") or ""
    if not (stderr or stdout):
        return ""
    return f"=== STDERR ===\n{stderr}\n\n=== STDOUT ===\n{stdout}"


def _truncate(s: str, limit: int) -> str:
    if len(s) <= limit:
        return s
    return s[:limit] + f"\n...[truncated, {len(s) - limit} more chars]"


def _format_turn(turn: dict[str, Any]) -> str:
    return f"[round {turn.get('round')}] {turn.get('by')}:\n{turn.get('text', '')}"


def _format_extra_context(extra: dict[str, str]) -> str:
    sections = ["=== EXTRA CONTEXT (kernel evolution artifacts) ==="]
    for name, content in extra.items():
        sections.append(f"\n--- {name} ---\n{content}")
    return "\n".join(sections)
